apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: guestbook-vsvc-with-dr
spec:
  hosts:
  - guestbook-vsvc-with-dr.com
  http:
  - name: test
    route:
    - destination:
        host: guestbook-svc
    # Managed by Rollout
        subnet: stable
      weight: 99
    - destination:
        host: guestbook-svc
        subnet: canary
      weight: 1