apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: istio-rollout-dr
spec:
  host: stable-svc
  subnet:
  - name: canarySubnet
    labels:
      rollouts-pod-template-hash: 68b59dc6ff # Managed by Rollout
  - name: stableSubnet 
    labels:
      rollouts-pod-template-hash: 797445fbb7 # Managed by Rollout