apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc
spec:
  gateways:
    - istio-rollout-gateway
  hosts:
    - istio-rollout.dev.argoproj.io
  http:
  - name: rewrite
    match:
    - uri:
        prefix: "/color"
    route:
    - destination:
        host: stable-svc
  - name: primary
    route:
    - destination:
        host: stable-svc
    # Below managed by Rollout
      weight: 100
    - destination:
        host: canary-svc
      weight: 0
  - name: rewrite-canary
    match:
    - uri:
        prefix: "/color"
      headers:
        end-user:
          exact: jason
    route:
    - destination:
        host: canary-svc