apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  metrics:
    - interval: 10s
      name: success-rate
      provider:
        prometheus:
          address: 'http://prometheus.istio-system:9090'
          query: |
            sum(
                irate(
                    istio_requests_total{
                        reporter="source",
                        destination_service=~"canary-svc.istio-rollout.svc.cluster.local",
                        response_code!~"5.*"
                    }[5m])
            ) / sum(
                irate(
                    istio_requests_total{
                        reporter="source",
                        destination_service=~"canary-svc.istio-rollout.svc.cluster.local"
                    }[5m]
                )
            )
      successCondition: 'result[0] > 0.90'
