apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: guestbook-vsvc-only-weight
spec:
  hosts:
  - istio-rollout.dev.argoproj.io
  http:
  - name: primary 
    route:
    - destination:
        host: stable-svc